[package]
name = "simple-kv-db"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "db"
path = "bin/db/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[crates.storage]
path = "crates/storage"

[crates.index]
path = "crates/index"

[crates.engine]
path = "crates/engine"

[crates.cli]
path = "crates/cli"