[workspace]
resolver = "2"
members = [
    "bin/db",
    "crates/storage",
    "crates/index", 
    "crates/engine",
    "crates/cli",
]

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
